"""Voice every line in addons/SpokenQuests/FollowupLines.lua with one ElevenLabs voice.

A stopgap so the follow-up matcher can be heard with the lines it actually matched, before
follow-up lines go through the site's generation and take history like every other clip.
Every speaker gets the same voice, whatever their race or gender.

Writes, both gitignored:
  addons/SpokenQuests/Sounds/followup/{broadcastTextID}.mp3
  addons/SpokenQuests/FollowupSounds.lua   the lengths the player queues by

    cd pipelines/quests
    PYTHONPATH=. uv run --no-project -q --with requests --with python-dotenv --with mutagen --with pandas \\
        python tools/generate_followup_audio.py --voice S3gcBld2OmAg0T50vCcc --model eleven_v4

Existing mp3s are kept, so a rerun only pays for what is missing; --force redoes them.
"""
import argparse
import json
import os
import re
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import mutagen
import requests

import tts_cli.env_vars  # noqa: F401 -- loads the two .env files, shell values winning
from tts_cli.tts_utils import REPLACE_DICT, TTSProcessor

REPO = Path(__file__).resolve().parents[3]
ADDON = REPO / 'addons' / 'SpokenQuests'
LINES = ADDON / 'FollowupLines.lua'
OUT_DIR = ADDON / 'Sounds' / 'followup'
LENGTHS = ADDON / 'FollowupSounds.lua'
GENERATION = REPO / 'pipelines' / 'quests' / 'voice' / 'generation.json'

ENTRY = re.compile(r'\{ id = (\d+),(?: speaker = (\d+),)? delay = \d+, chat = "\w+", '
                   r'male = "((?:[^"\\]|\\.)*)"')


def load_lines():
    """{broadcastTextID: (speaker, male text)}; one id can sit under several quests."""
    lines = {}
    for m in ENTRY.finditer(LINES.read_text()):
        text = m.group(3).encode().decode('unicode_escape')
        lines.setdefault(int(m.group(1)), (int(m.group(2) or 0), text))
    return lines


def speakable(text):
    # The male option of $g: the one voice is male. The rest are the corpus's own
    # stand-ins, so "$n" is read as "adventurer" here exactly as in quest text.
    text, _ = TTSProcessor().handle_gender_options(text)
    for token, word in REPLACE_DICT.items():
        text = text.replace(token, word)
    return re.sub(r'\s+', ' ', text).strip()


def duration(path):
    return round(mutagen.File(path).info.length, 3)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--voice', required=True, help='ElevenLabs voice_id')
    p.add_argument('--model', default='eleven_v4')
    p.add_argument('--limit', type=int, help='only the first N ids, for a trial')
    p.add_argument('--force', action='store_true')
    p.add_argument('--workers', type=int, default=4)
    args = p.parse_args()

    key = os.getenv('ELEVENLABS_API_KEY')
    if not key:
        sys.exit('ELEVENLABS_API_KEY is not set, in the shell or either .env')
    settings = json.loads(GENERATION.read_text())['voice_settings']

    lines = load_lines()
    ids = sorted(lines)[:args.limit] if args.limit else sorted(lines)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    def one(line_id):
        speaker, raw = lines[line_id]
        target = OUT_DIR / f'{line_id}.mp3'
        # A "%s" is the speaker's name spliced in by the server, and the only line carrying
        # one reads as narration rather than speech.
        if '%s' in raw:
            return line_id, 'skipped'
        if target.exists() and not args.force:
            return line_id, 'kept'
        body = {'text': speakable(raw), 'model_id': args.model, 'voice_settings': settings}
        if speaker:
            # Same seed per NPC, as generation.json's "npc" strategy does on the site.
            body['seed'] = speaker
        r = requests.post(
            f'https://api.elevenlabs.io/v1/text-to-speech/{args.voice}?output_format=mp3_44100_128',
            headers={'xi-api-key': key}, json=body, timeout=120)
        if r.status_code != 200:
            return line_id, f'failed {r.status_code}: {r.text[:200]}'
        target.write_bytes(r.content)
        return line_id, 'generated'

    failed = 0
    with ThreadPoolExecutor(args.workers) as pool:
        for line_id, status in pool.map(one, ids):
            if status.startswith('failed'):
                failed += 1
            if status != 'kept':
                print(line_id, status, flush=True)

    # Lengths for every mp3 on disk, not just this run's, so a --limit trial followed by a
    # full run leaves one complete table.
    lengths = {int(f.stem): duration(f) for f in OUT_DIR.glob('*.mp3')}
    rows = '\n'.join(f'    [{i}] = {lengths[i]},' for i in sorted(lengths))
    LENGTHS.write_text(
        'setfenv(1, VoiceOver)\n\n'
        '-- Generated by pipelines/quests/tools/generate_followup_audio.py; do not edit by hand.\n'
        '-- Seconds per Sounds/followup/{broadcastTextID}.mp3, for the player queue.\n'
        f'FollowupSoundLengths = {{\n{rows}\n}}\n')
    print(f'{len(lengths)} clips on disk, {failed} failed')
    sys.exit(1 if failed else 0)


if __name__ == '__main__':
    main()
